### ISSUE TITLE
ImportError: cannot import name NavigationToolbar2QTAg

### ISSUE THREAD

**Issue by laserkelvin** [jnicoleoliveira/SPECData#4]
## Hi Jasmine,

__Love the program.__

Ran into an issue having this to work on Mac OSX Version 10.11.6. I am running Anaconda Python 2.7.13.

```
Traceback (most recent call last):
  File "/Users/kelvin/Google Drive/Git/specdata/SPECData/app/dialogs/dialog___load_experiment.py", line 53, in load
    self.load_experiment(text[1], text[2])
  File "/Users/kelvin/Google Drive/Git/specdata/SPECData/app/dialogs/dialog___load_experiment.py", line 65, in load_experiment
    from dialog___open_experiment_view import OpenExperimentView
  File "/Users/kelvin/Google Drive/Git/specdata/SPECData/app/dialogs/dialog___open_experiment_view.py", line 3, in <module>
    from dialog___experiment_view import ExperimentView
  File "/Users/kelvin/Google Drive/Git/specdata/SPECData/app/dialogs/dialog___experiment_view.py", line 9, in <module>
    from pyqtgraph.widgets.MatplotlibWidget import MatplotlibWidget
  File "/Users/kelvin/anaconda3/envs/SPECData/lib/python2.7/site-packages/pyqtgraph/widgets/MatplotlibWidget.py", line 8, in <module>
    from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg as NavigationToolbar
ImportError: cannot import name NavigationToolbar2QTAgg
```

Plz help.

**Comment by jnicoleoliveira** [comment]
Hi Kelvin, 
Happy to hear you are enjoying the software!

Your issue has to do with the version of Matplotlib you are using - there are some name changes in the library that need to be updated manually. 

In the file, where the error is occuring:
`/Users/kelvin/anaconda3/envs/SPECData/lib/python2.7/site-packages/pyqtgraph/widgets/MatplotlibWidget.py`

Change the line:
`from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg as NavigationToolbar
`
to:
`from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT
`

[[source](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/2)]
